[config]

[templates.vicinae]
input_path = '~/.config/matugen/templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'

# VS Code matugen extension
[templates.vscode-raw]
input_path = './templates/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = './templates/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'

