--enable-features=WaylandWindowDecorations,AllowQt
# --ozone-platform-hint=wayland (removed in Electron 38)
--ozone-platform=wayland
# GTK4 works better on Wayland.
--gtk-version=4
--enable-wayland-ime
--wayland-text-input-version=3
